# -*- mode: ruby -*-
# vi: set ft=ruby et ts=2 sts=2 sw=2 :

# centos7 vm

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  #config.vm.hostname = "foo"

  config.vm.provision :ansible do |ansible|
    # Run a no-op playbook to create the inventory file.
    # Based on that, one can run ansible without vagrant.
    ansible.playbook = "no-op-playbook.yml"
  end
end
